### ISSUE TITLE
Question on the compilation with different version of cuda or pytorch

### ISSUE THREAD

**Issue by PeiqinZhuang** [SHI-Labs/Neighborhood-Attention-Transformer#5] opened 2022-04-18 08:03 UTC
Thanks for this work. I just wonder if the Cuda source code could be compiled with different versions of PyTorch or Cuda driver which you recommend? Right now, I have some problems with older pytorch and cuda driver for the compilation.

**Comment by alihassanijr** [comment] 2022-04-18 17:02
Hi, thank you for your interest.
It should be compatible with recent PyTorch and CUDA versions. We've only tried torch 1.8 and above, and strongly recommend the latest, torch 1.11.
Could you share the error you're facing and the torch/cuda versions you have?

**Comment by PeiqinZhuang** [comment] 2022-04-19 00:13
> Hi, thank you for your interest. It should be compatible with recent PyTorch and CUDA versions. We've only tried torch 1.8 and above, and strongly recommend the latest, torch 1.11. Could you share the error you're facing and the torch/cuda versions you have?

Hi, Thanks for the reply. I attach the screenshot with the error. Actually, I use torch 1.8 and Cuda driver 10.1
![截屏2022-04-19 上午10 10 17](https://user-images.githubusercontent.com/19246721/163896109-769ff188-83f8-4c68-ad85-9ce997294e79.png)

**Comment by stevenwalton** [comment] 2022-04-19 01:23
Hi Peiqin, what GPU are you using? I don't think we have tested that cuda driver but are looking into it.

**Comment by alihassanijr** [comment] 2022-04-19 01:41
This is really strange. Seems to be more of a torch error than anything else. Would you mind also sharing the entire error and the command you ran, and as many details as possible on the environment, so we try and see if we can reproduce it on our end?

**Comment by PeiqinZhuang** [comment] 2022-04-19 03:31
> Hi Peiqin, what GPU are you using? I don't think we have tested that cuda driver but are looking into it.

Hi, I just compiled it on V100.

**Comment by alihassanijr** [comment] 2022-04-27 18:16
Hi,
Could you share the command you ran and your environment details so we can look into the issue?

**Comment by PeiqinZhuang** [comment] 2022-04-29 01:31
> Hi, Could you share the command you ran and your environment details so we can look into the issue?

Hi, I just solved this problem by creating a new python environment. It seems that there exist some problems with my previous environment.

**Comment by alihassanijr** [comment] 2022-04-29 01:40
Thank you for your response. 
If you don't have any other questions, feel free to close this issue. 
Otherwise feel free to ask.

**Comment by alihassanijr** [comment] 2022-05-08 20:10
Closing this due to inactivity. If you still have questions feel free to open it back up.

**Closed as completed by alihassanijr** 2022-05-08 20:10 UTC
Labels: question
